CREATE TABLE BOARD(
	BID INT PRIMARY KEY,
	TITLE VARCHAR(20) NOT NULL,
	WRITER VARCHAR(20) NOT NULL,
	CONTENT VARCHAR(100) NOT NULL,
	CNT INT DEFAULT 0,
	IMG VARCHAR(500),
	REGDATE DATE DEFAULT SYSDATE
);

	IMG VARCHAR(500) DEFAULT "default.jpg",
-- 이미지를 올리지 않는 경우 default 값 설정

INSERT INTO BOARD(BID,TITLE,WRITER,CONTENT) VALUES(1,'제목','관리자','내용');

DROP TABLE BOARD;
SELECT * FROM BOARD;